[package]
name = "clap-config"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Alexander Apatiga <dapatiga@gmail.com>"]

[lib]
name="clap_config"
proc-macro = false
crate-type=["lib"]


[features]


[dependencies]
config = "*"
serde_json = "*"
serde = "*"